### ISSUE TITLE
restart staticd and zebra one after other, routes are not installed in rib.

### ISSUE THREAD

**Issue by gpnaveen** [pushpasis/frr#83]
Build : from PR 10000 ubuntu 18.04 amd .

Script:
PR 10000
Topotest test case test_mgmt_chaos_kill_daemon.

With the below change : 
    step("Kill static daemon on R2.")
    kill_router_daemons(tgen, "r1", ["staticd"])

    step("Bring up staticd daemon on R2.")
    start_router_daemons(tgen, "r1", ["staticd"])

    step("Verify routes are intact in zebra.")
    result = verify_rib(tgen, "ipv4", dut, input_dict_4, protocol=protocol)
    assert (
        result is True
    ), "Testcase {} : Failed" "Error: Routes is missing in RIB".format(tc_name)

=======> Kill and start zebra here and check the result.

    step("Kill mgmt daemon on R2.")
    kill_router_daemons(tgen, "r1", ["mgmtd"])

    step("Bring up zebra daemon on R2.")
    start_router_daemons(tgen, "r1", ["mgmtd"])

Routes are not installed in zebra after this step, but the same is present in the running config.

**Comment by ranjanyash54** [comment]
Hi Naveen.
If you kill zebra then the watchfrr should automatically start it. In that case, the routes and configurations are restored.

But if watchfrr is not started and zebra is manually stopped and started then the routes are restored. This is the case with a normal router as well. 

Please modify your scripts so that watchfrr restarts zebra.
@gpnaveen
